plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id("com.google.dagger.hilt.android")                // Hilt plugin
    id("kotlin-kapt")
    id ("com.google.gms.google-services")
    id ("com.google.firebase.crashlytics")
}

android {
    namespace 'com.warrior.oc.ca'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.warrior.oc.ca"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner= "androidx.test.runner.AndroidJUnitRunner"
        def formattedDate = new Date().format('MM.dd.yyyy')
        archivesBaseName = "ST259_Brush_Jiaemu_Cat_v${versionName}_${formattedDate}"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    buildFeatures {
        viewBinding true
        dataBinding true
    }
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = true
        }
        abi {
            enableSplit = true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.activity)
    implementation("androidx.viewpager2:viewpager2:1.1.0")
    implementation(libs.androidx.constraintlayout)
    implementation("androidx.camera:camera-camera2:1.6.2")
    implementation("androidx.camera:camera-lifecycle:1.6.2")
    implementation("androidx.camera:camera-view:1.6.2")
    implementation(libs.androidx.lifecycle.viewmodel.ktx)

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)


    // Hilt
    implementation(libs.hilt.android)
    kapt(libs.hilt.compiler)

    // Review app
    implementation("com.google.android.play:review-ktx:2.0.2")

    // Glide
    implementation("com.github.bumptech.glide:glide:4.15.1")
    kapt("com.github.bumptech.glide:compiler:4.15.1")

    // UI Components
    implementation("com.tbuonomo:dotsindicator:5.1.0")
    implementation("androidx.cardview:cardview:1.0.0")
    implementation("com.github.ome450901:SimpleRatingBar:1.5.1")
    implementation("com.airbnb.android:lottie:6.7.1")
    implementation("com.github.lehongquyme:roundedframelayout:release~v1.1")

    // Kotlin Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")

    // Lifecycle
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.6")

    // Firebase
    implementation(platform("com.google.firebase:firebase-bom:33.7.0"))
    implementation("com.google.firebase:firebase-analytics-ktx")
    implementation("com.google.firebase:firebase-crashlytics-ktx")

}
